all:
	$(MAKE) -f Makefile.main2 all

main2Build:
	$(MAKE) -f Makefile.main2 all


main2Run:
	$(MAKE) -f Makefile.main2 run

clean:
	$(MAKE) -f Makefile.main2 clean

fclean:
	$(MAKE) -f Makefile.main2 fclean

re: fclean all

.PHONY: all main2Build main2Run clean fclean re
