all:
	$(MAKE) -f Makefile.main all

mainBuild:
	$(MAKE) -f Makefile.main all


mainRun:
	$(MAKE) -f Makefile.main run

clean:
	$(MAKE) -f Makefile.main clean

fclean:
	$(MAKE) -f Makefile.main fclean

re: fclean all

.PHONY: all mainBuild mainRun clean fclean re
